spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/proj_wechat?serverTimezone=UTC
    username: root
    password: 123
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
server:
  servlet:
    context-path: /sell